// generated by casm
#include "drally.h"

__DWORD__ __GET_TIMER_TICKS(void);

__DWORD__ ___61bb8h(__DWORD__ A1){
/*
		push    18h
		call    near __CHK
		push    ebx
		push    ecx
		push    edx
		push    esi
		push    edi
		mov     ecx, eax
		lea     ebx, [eax+4]
		mov     eax, ebx

	push 	edx
	push 	ecx
	push 	eax
		call    inp_
	add 	esp, 4
	pop 	ecx
	pop 	edx

		mov     edi, eax
		mov     edx, 10h
		mov     eax, ebx

	push 	ecx
	push 	edx
	push 	eax
		call    outp_
	add 	esp, 8
	pop 	ecx

		lea     esi, [ecx+6]
		mov     eax, esi

	push 	edx
	push 	ecx
	push 	eax
		call    inp_
	add 	esp, 4
	pop 	ecx
	pop 	edx

		test    al, 0f0h
		je      short ___61bf6h
		xor     eax, eax
		jmp     near ___61cc9h
___61bf6h:
		mov     edx, 1fh
		mov     eax, ebx

	push 	ecx
	push 	edx
	push 	eax
		call    outp_
	add 	esp, 8
	pop 	ecx

		mov     eax, esi

	push 	edx
	push 	ecx
	push 	eax
		call    inp_
	add 	esp, 4
	pop 	ecx
	pop 	edx

		and     eax, 0f0h
		cmp     eax, __DWORD__ 0f0h
		je      short ___61c1dh
		xor     eax, eax
		pop     edi
		pop     esi
		pop     edx
		pop     ecx
		pop     ebx
		retn    
___61c1dh:
		mov     edx, edi
		mov     eax, ebx

	push 	ecx
	push 	edx
	push 	eax
		call    outp_
	add 	esp, 8
	pop 	ecx

		lea     ebx, [ecx+7]
		mov     eax, ebx

	push 	edx
	push 	ecx
	push 	eax
		call    inp_
	add 	esp, 4
	pop 	ecx
	pop 	edx

		mov     esi, eax
		mov     edx, 55h
		mov     eax, ebx

	push 	ecx
	push 	edx
	push 	eax
		call    outp_
	add 	esp, 8
	pop 	ecx

		mov     eax, ebx

	push 	edx
	push 	ecx
	push 	eax
		call    inp_
	add 	esp, 4
	pop 	ecx
	pop 	edx

		cmp     eax, byte 55h
		je      short ___61c55h
		mov     eax, 1
		pop     edi
		pop     esi
		pop     edx
		pop     ecx
		pop     ebx
		retn    
___61c55h:
		mov     edx, 0aah
		mov     eax, ebx

	push 	ecx
	push 	edx
	push 	eax
		call    outp_
	add 	esp, 8
	pop 	ecx

		mov     eax, ebx

	push 	edx
	push 	ecx
	push 	eax
		call    inp_
	add 	esp, 4
	pop 	ecx
	pop 	edx

		cmp     eax, __DWORD__ 0aah
		je      short ___61c7ah
		mov     eax, 1
		pop     edi
		pop     esi
		pop     edx
		pop     ecx
		pop     ebx
		retn    
___61c7ah:
		mov     edx, esi
		mov     eax, ebx

	push 	ecx
	push 	edx
	push 	eax
		call    outp_
	add 	esp, 8
	pop 	ecx

		lea     ebx, [ecx+2]
		mov     edx, 1
		mov     eax, ebx

	push 	ecx
	push 	edx
	push 	eax
		call    outp_
	add 	esp, 8
	pop 	ecx

		mov     eax, ebx

	push 	edx
	push 	ecx
	push 	eax
		call    inp_
	add 	esp, 4
	pop 	ecx
	pop 	edx

		mov     ecx, eax
		xor     edx, edx
		mov     eax, ebx

	push 	ecx
	push 	edx
	push 	eax
		call    outp_
	add 	esp, 8
	pop 	ecx

		test    cl, 80h
		jne     short ___61cb4h
		mov     eax, 2
		pop     edi
		pop     esi
		pop     edx
		pop     ecx
		pop     ebx
		retn    
___61cb4h:
		test    cl, 40h
		jne     short ___61cc4h
		mov     eax, 3
		pop     edi
		pop     esi
		pop     edx
		pop     ecx
		pop     ebx
		retn    
___61cc4h:
		mov     eax, 4
___61cc9h:
		pop     edi
		pop     esi
		pop     edx
		pop     ecx
		pop     ebx
		retn    
*/
    return 4;
}

__DWORD__ ___61b88h(__DWORD__ A1){

	__DWORD__ 	ticks;

	___61bb8h(A1);

	ticks = 1 + __GET_TIMER_TICKS();

	while(ticks > __GET_TIMER_TICKS());

	return ___61bb8h(A1);
}
