// generated by casm
#include "drally.h"

dword __GET_TIMER_TICKS(void);
dword ___61bb8h(dword);

dword ___61b88h(dword A1){

	dword 	ticks;

	___61bb8h(A1);

	ticks = 1 + __GET_TIMER_TICKS();

	while(ticks > __GET_TIMER_TICKS());

	return ___61bb8h(A1);
}
