#!/bin/sh

cp drally.exe ~/DEATHRAL/drally.exe
cp drally.le ~/DEATHRAL/drally.le

# dosbox ~/DEATHRAL/drally.exe
dosbox -c "mount C ~/DEATHRAL" -c "C:" -c "DOS4G.EXE drally.le"
# dosbox -c "mount C ~/DEATHRAL" -c "C:" -c "pmwbind /B /DPMWRALLY.EXE DRALLY.LE" -c "PMWRALLY.EXE"
