#ifndef __SFX_H
#define __SFX_H

#define SFX_MENU                    0//0x0100      // MEN-SAM
#define SFX_SPEED_MAKES_ME_DIZZY    (0x01|SFX_MENU)
#define SFX_I_LIVE_TO_RIDE          (0x02|SFX_MENU)
#define SFX_PETROL_IN_MY_VEINS      (0x03|SFX_MENU)
#define SFX_NEW_CAR_BOUGHT          (0x04|SFX_MENU)
#define SFX_SPECIAL_OFFER           (0x05|SFX_MENU)
#define SFX_LETS_ROCK               (0x06|SFX_MENU)
#define SFX_SIGNUP_BRAKES           (0x15|SFX_MENU)
#define SFX_CLICK_1                 (0x16|SFX_MENU)
#define SFX_LAUGHTER                (0x17|SFX_MENU)
#define SFX_SIGNUP_ENGINE_ON        (0x18|SFX_MENU)
#define SFX_CLICK_2                 (0x19|SFX_MENU)
#define SFX_CLICK_3                 (0x1a|SFX_MENU)
#define SFX_CLICK_4                 (0x1c|SFX_MENU)
#define SFX_BUMMER                  (0x1d|SFX_MENU)
#define SFX_ANVIL                   (0x1f|SFX_MENU)

#define SFX_RACE                    0//0x0200      // GEN-EFE
#define SFX_LOOK_OUT                (0x01|SFX_RACE)
#define SFX_FINAL_LAP               (0x02|SFX_RACE)
#define SFX_GET_READY               (0x03|SFX_RACE)
#define SFX_LAP_RECORD              (0x04|SFX_RACE)
#define SFX_RACE_OVER               (0x05|SFX_RACE)
#define SFX_SIENI                   (0x06|SFX_RACE)
#define SFX_KILLED_SPECTATOR_1      (0x07|SFX_RACE)
#define SFX_KILLED_SPECTATOR_2      (0x08|SFX_RACE)
#define SFX_KILLED_SPECTATOR_3      (0x09|SFX_RACE)
#define SFX_METAL_HIT               (0x0a|SFX_RACE)
#define SFX_CAR_HIT_1               (0x0b|SFX_RACE)
#define SFX_KLONK_2                 (0x0c|SFX_RACE)
#define SFX_METAL                   (0x0d|SFX_RACE)
#define SFX_HIT_2                   (0x0e|SFX_RACE)
#define SFX_CAR_HIT_2               (0x0f|SFX_RACE)
#define SFX_CAR_HIT_3               (0x10|SFX_RACE)
#define SFX_MONSTER                 (0x11|SFX_RACE)
#define SFX_MINE                    (0x12|SFX_RACE)
#define SFX_SHOT_2                  (0x13|SFX_RACE)
#define SFX_SHOT_3                  (0x14|SFX_RACE)
#define SFX_EXPLOSION               (0x15|SFX_RACE)
#define SFX_YOUVE_BEEN_LAPPED       (0x16|SFX_RACE)
#define SFX_MINE_EXPLOSION          (0x17|SFX_RACE)
#define SFX_KUPLA                   (0x19|SFX_RACE)
#define SFX_PICKUP                  (0x1a|SFX_RACE)
#define SFX_SEDAN                   (0x1b|SFX_RACE)
#define SFX_CAMARO                  (0x1c|SFX_RACE)
#define SFX_PORSCHE                 (0x1d|SFX_RACE)
#define SFX_DELIVERATOR             (0x1e|SFX_RACE)
#define SFX_HAIL_TO_THE_KING        (0x1f|SFX_RACE)
#define SFX_THIS_SUCKS              (0x20|SFX_RACE)
#define SFX_HORN_1                  (0x21|SFX_RACE)
#define SFX_HORN_2                  (0x22|SFX_RACE)
#define SFX_BRAKES                  (0x25|SFX_RACE)
#define SFX_BEEP                    (0x2c|SFX_RACE)

#endif // __SFX_H
